trigger:
- master
strategy:
   matrix:
    linux:
     imagename: "ubuntu-latest"
     jdkVersion: "1.10"
    windows:
     imagename: "windows-latest"
     jdkVersion: "1.11"
   maxParallel: 2
pool:
  vmImage: $(imagename)

steps:
- task: Maven@3
  inputs:
    mavenPomFile: "pom.xml"
    mavenOptions: "-Xmx3072m"
    javaHomeOption: "JDKVersion"
    jdkVersionOption: $(jdkVersion)
    jdkArchitectureOption: "x64"
    publishJUnitResults: true
    testResultsFiles: "**/TEST-*.xml"
    goals: "package"
    sonarQubeRunAnalysis: true